# Generated by Django 2.2 on 2019-04-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0003_hobby'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.CharField(default='https://www.google.com', max_length=100),
        ),
    ]
