# Generated by Django 3.0.1 on 2020-03-06 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0004_project_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='duration',
            field=models.CharField(default='2018-present', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.TextField(default='Boston, MA'),
        ),
    ]
